### PR TITLE
Big Library Update

### PR DESCRIPTION
**Pull request by stephenhensley**
Many changes:

* Combines DaisySP and the Daisy Audio library (formerly two separate repos)
* Adds board support for Pod breakout board
* Adds ports of libdaisy Pod examples for Arduino
* Migrates DaisySP examples here

Thing to still do (not sure if they fit in the scope of this or not yet):

* Organization of Seed examples by type/function since there are a lot of them (i.e. Hardware, Processor, Generator, Modifier, Utility, etc.)
* Add Patch support (would require driver/lib for SSD1309 OLED)
* Add Field/Petal support (would require driver/lib for PCA9685, CD4021 Mux, CD4051 Input shift)
* SDRAM support (still related to #4)

The SDRAM support _should_ be added via stm32duino board variant, but it wasn't included in the first release. A temporary band-aid would be nice, but we should also make a PR for the Arduino_Core asap.

### CODE REVIEW

**Comment by andrewikenberry** [comment]
- Change library name to DaisyDuino 
- Can we get syntax highlighting for classes like DaisyPod?
- Is it possible to combine the two init functions so that pod.Init already calls the Daisy.init like it does in libDaisy?
- Make sure our library follows [these guidelines](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ) so that we can get it added to the library manager.

**Comment by stephenhensley** [comment]
Wrt a single call to `DAISY.init()` it would be great if we could return a `Hardware` object or something (the equivalent of the current `DaisyPod` class). 

The only ways I can think to do this would be to either:
* Have a generic `DaisyHardware` class that can be initialized as Pod, Patch, etc. (just different inits and numbers of interface elements), though this wouldn't be able to easily support the Displays, and external peripherals with out a bunch of `NULL` objects (which could be fine).
* Create a generice `DaisyHardware` base class that `DaisyPod`, etc. inherit from. (Though, I'd prefer to avoid inheritance.)

**Comment by andrewikenberry** [comment]
This looks a lot better.

Things that still need syntax highlighting:

- Process methods (osc.Process)
- SetFreq, SetAmp
- DaisyHardware class
- DaisyHardware methods (DebounceControls, etc.)
- DSP helper functions (mtof, DSY_CLAMP, etc.)

**Comment by andrewikenberry** [comment]
Also: 

- url in library.properties should be https://github.com/electro-smith/DaisyDuino/

**Comment by andrewikenberry** [comment]
- Oscillator seed example is set up for Patch hw and doesn't build due to undefined reference to "pitchknob"

**Comment by andrewikenberry** [comment]
Boom!
Everything works and looks great.

**Pull request merged**
